using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EthereumRpc
{
    public enum RpcMethod
    {
        [Description("web3_clientVersion")]
        web3_clientVersion,
        [Description("web3_sha3")]
        web3_sha3,
        [Description("net_version")]
        net_version,
        [Description("net_peerCount")]
        net_peerCount,
        [Description("net_listening")]
        net_listening,
        [Description("eth_protocolVersion")]
        eth_protocolVersion,
        [Description("eth_syncing")]
        eth_syncing,
        [Description("eth_coinbase")]
        eth_coinbase,
        [Description("eth_mining")]
        eth_mining,
        [Description("eth_hashrate")]
        eth_hashrate,
        [Description("eth_gasPrice")]
        eth_gasPrice,
        [Description("eth_accounts")]
        eth_accounts,
        [Description("eth_blockNumber")]
        eth_blockNumber,
        [Description("eth_getBalance")]
        eth_getBalance,
        [Description("eth_getStorageAt")]
        eth_getStorageAt,
        [Description("eth_getTransactionCount")]
        eth_getTransactionCount,
        [Description("eth_getBlockTransactionCountByHash")]
        eth_getBlockTransactionCountByHash,
        [Description("eth_getBlockTransactionCountByNumber")]
        eth_getBlockTransactionCountByNumber,
        [Description("eth_getUncleCountByBlockHash")]
        eth_getUncleCountByBlockHash,
        [Description("eth_getUncleCountByBlockNumber")]
        eth_getUncleCountByBlockNumber,
        [Description("eth_getCode")]
        eth_getCode,
        [Description("eth_sign")]
        eth_sign,
        [Description("eth_sendTransaction")]
        eth_sendTransaction,
        [Description("eth_sendRawTransaction")]
        eth_sendRawTransaction,
        [Description("eth_call")]
        eth_call,
        [Description("eth_estimateGas")]
        eth_estimateGas,
        [Description("eth_getBlockByHash")]
        eth_getBlockByHash,
        [Description("eth_getBlockByNumber")]
        eth_getBlockByNumber,
        [Description("eth_getTransactionByHash")]
        eth_getTransactionByHash,
        [Description("eth_getTransactionByBlockHashAndIndex")]
        eth_getTransactionByBlockHashAndIndex,
        [Description("eth_getTransactionByBlockNumberAndIndex")]
        eth_getTransactionByBlockNumberAndIndex,
        [Description("eth_getTransactionReceipt")]
        eth_getTransactionReceipt,
        [Description("eth_getUncleByBlockHashAndIndex")]
        eth_getUncleByBlockHashAndIndex,
        [Description("eth_getUncleByBlockNumberAndIndex")]
        eth_getUncleByBlockNumberAndIndex,
        [Description("eth_getCompilers")]
        eth_getCompilers,
        [Description("eth_compileLLL")]
        eth_compileLLL,
        [Description("eth_compileSolidity")]
        eth_compileSolidity,
        [Description("eth_compileSerpent")]
        eth_compileSerpent,
        [Description("eth_newFilter")]
        eth_newFilter,
        [Description("eth_newBlockFilter")]
        eth_newBlockFilter,
        [Description("eth_newPendingTransactionFilter")]
        eth_newPendingTransactionFilter,
        [Description("eth_uninstallFilter")]
        eth_uninstallFilter,
        [Description("eth_getFilterChanges")]
        eth_getFilterChanges,
        [Description("eth_getFilterLogs")]
        eth_getFilterLogs,
        [Description("eth_getLogs")]
        eth_getLogs,
        [Description("eth_getWork")]
        eth_getWork,
        [Description("eth_submitWork")]
        eth_submitWork,
        [Description("eth_submitHashrate")]
        eth_submitHashrate,
        [Description("db_putString")]
        db_putString,
        [Description("db_getString")]
        db_getString,
        [Description("db_putHex")]
        db_putHex,
        [Description("db_getHex")]
        db_getHex,
        [Description("shh_post")]
        shh_post,
        [Description("shh_version")]
        shh_version,
        [Description("shh_newIdentity")]
        shh_newIdentity,
        [Description("shh_hasIdentity")]
        shh_hasIdentity,
        [Description("shh_newGroup")]
        shh_newGroup,
        [Description("shh_addToGroup")]
        shh_addToGroup,
        [Description("shh_newFilter")]
        shh_newFilter,
        [Description("shh_uninstallFilter")]
        shh_uninstallFilter,
        [Description("shh_getFilterChanges")]
        shh_getFilterChanges,
        [Description("shh_getMessages")]
        shh_getMessages,
        [Description("personal_newAccount")]
        personal_newAccount,
        [Description("personal_unlockAccount")]
        personal_unlockAccount
    }
}
